### ISSUE TITLE
Allow output to be useful for Zabbix

### ISSUE THREAD

**Issue by mrimann** [mrimann/check_dnssec_expiry#12]
As proposed by @gryphius [tweet](https://twitter.com/mailerda3mon/status/989375304065044480):

> With small modifications, @mrimann 's check_dnssec_expiry nagios plugin works as #Zabbix external check as well. Replace the last 10 lines with "echo $maxRemainingLifetime"

I think this should be easily possible to add this as a command line switch, to "enable Zabbix mode" for the output.

**Comment by gryphius** [comment]
maybe we could have two switches, one for printing the remaining percentage and one for the absolute duration in seconds.  In my quick and dirty test I duplicated the whole script, but of course it would be nicer if we added both options into one
